services:
  bot:
    image: eclipse-temurin:11-jdk-alpine
    command: java -cp /analyzer.jar de.prkz.twitch.loki.TwitchChatLokiClient /loki-client.properties
    volumes:
      - ./loki-client.properties:/loki-client.properties:ro
      - ./build/libs/twitch-chat-analyzer-SNAPSHOT-all.jar:/analyzer.jar:ro
    restart: unless-stopped

  loki:
    image: grafana/loki
    restart: unless-stopped
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-grafana}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-password}
      GF_PATH_PROVISIONING: /etc/grafana/provisioning
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
    ports:
      - "${GRAFANA_EXTERNAL_PORT:-3000}:3000"

volumes:
  loki_data:
  grafana_data:
