version: "2.2"
services:
  #----------------------------------------------------------------------------
  # Chat Bot
  #----------------------------------------------------------------------------
  bot:
    image: openjdk:8-alpine
    command: java -cp /analyzer.jar de.prkz.twitch.emoteanalyser.bot.Bot /bot.properties
    container_name: tca_bot
    volumes:
      - ./bot.properties:/bot.properties:ro
      - ./build/libs/twitch-chat-analyzer-1.1-SNAPSHOT.jar:/analyzer.jar:ro
    links:
      - kafka
    restart: always

  #----------------------------------------------------------------------------
  # Zookeeper
  #----------------------------------------------------------------------------
  zookeeper:
    image: zookeeper
    container_name: tca_zookeeper
    expose:
      - "2181"
    restart: always
  
  #----------------------------------------------------------------------------
  # Kafka
  #----------------------------------------------------------------------------
  kafka:
    build: ./kafka
    entrypoint: wait-for.sh --wait-for zookeeper:2181 --delay 5s
    command: start-kafka.sh
    container_name: tca_kafka
    volumes:
      - ./kafka-storage:/kafka
    expose:
      - "9092"
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_BROKER_ID: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_RETENTION_MINUTES: 43200
      KAFKA_LOG_RETENTION_HOURS: -1
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
    links:
      - zookeeper
    restart: always
  
  #----------------------------------------------------------------------------
  # Flink
  #----------------------------------------------------------------------------
  flink-jobmanager:
    build: ./flink
    command: jobmanager
    container_name: tca_flink-jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
    volumes:
      # flink-conf.yaml is altered in docker entrypoint script, so it is added in Dockerfile
      - ./flink-data:/data
    links:
      - postgres
    restart: always
  
  flink-taskmanager:
    build: ./flink
    command: taskmanager
    container_name: tca_flink-taskmanager
    expose:
      - "6121"
      - "6122"
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
      # Adjust as needed
      TASK_MANAGER_NUMBER_OF_TASK_SLOTS: 1
    volumes:
      # flink-conf.yaml is altered in docker entrypoint script, so it is added in Dockerfile
      # Same directory, so JM can delete TM checkpoint data
      - ./flink-data:/data
    links:
      - flink-jobmanager
      - postgres
      - zookeeper
      - kafka
    restart: always

  #----------------------------------------------------------------------------
  # Postgres
  #----------------------------------------------------------------------------
  postgres:
    image: postgres:13.0
    container_name: tca_postgres
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitch
    volumes:
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always

  #----------------------------------------------------------------------------
  # Dashboard / Frontend
  #----------------------------------------------------------------------------
  dashboard:
    image: dashboard
    build: ./dashboard
    container_name: tca_dashboard
    ports:
      - "8082:80"
    volumes:
      - ./dashboard:/var/www/html
      - ./dashboard/php.ini:/usr/local/etc/php/php-dashboard.ini:ro
    links:
      - postgres
    restart: always

volumes:
  postgres-data:
