services:
  #----------------------------------------------------------------------------
  # Chat Bot
  #----------------------------------------------------------------------------
  bot:
    image: eclipse-temurin:11-jdk-alpine
    command: java -cp /analyzer.jar de.prkz.twitch.emoteanalyser.bot.Bot /bot.properties
    volumes:
      - ./bot.properties:/bot.properties:ro
      - ./build/libs/twitch-chat-analyzer-SNAPSHOT-all.jar:/analyzer.jar:ro
    restart: unless-stopped
    depends_on:
      - kafka
      - postgres

  #----------------------------------------------------------------------------
  # Zookeeper
  #----------------------------------------------------------------------------
  zookeeper:
    image: zookeeper
    expose:
      - "2181"
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog
    restart: unless-stopped
  
  #----------------------------------------------------------------------------
  # Kafka
  #----------------------------------------------------------------------------
  kafka:
    build: ./kafka
    entrypoint: wait-for.sh --wait-for zookeeper:2181 --delay 5s
    command: start-kafka.sh
    volumes:
      - ./kafka-storage:/kafka
    expose:
      - "9092"
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_BROKER_ID: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_RETENTION_MINUTES: 43200
      KAFKA_LOG_RETENTION_HOURS: -1
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms256M"
    restart: unless-stopped
    depends_on:
      - zookeeper
  
  #----------------------------------------------------------------------------
  # Flink
  #----------------------------------------------------------------------------
  flink-jobmanager:
    image: flink:1.15.2
    command: jobmanager
    expose:
      - "6123"
    ports:
      - "8081:8081"
    environment:
      FLINK_PROPERTIES: |
        web.port: 8081
        jobmanager.rpc.address: flink-jobmanager
        jobmanager.rpc.port: 6123
        jobmanager.memory.process.size: 1600m
    volumes:
      - ./flink-data:/data
    restart: unless-stopped
  
  flink-taskmanager:
    image: flink:1.15.2
    command: taskmanager
    expose:
      - "6121"
      - "6122"
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: flink-jobmanager
        jobmanager.rpc.port: 6123
        
        # Adjust as needed
        taskmanager.numberOfTaskSlots: 4
        
        taskmanager.process.size: 1728m
        taskmanager.memory.network.min: 32mb
        taskmanager.memory.network.fraction: 0.03
    volumes:
      - ./flink/log4j-cli.properties:/opt/flink/conf/log4j-cli.properties:ro
      # Same directory as in JM, so JM can delete TM checkpoint data
      - ./flink-data:/data
    restart: unless-stopped
    depends_on:
      - flink-jobmanager

  #----------------------------------------------------------------------------
  # Postgres
  #----------------------------------------------------------------------------
  postgres:
    image: postgres:15
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: twitch
    volumes:
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: unless-stopped

  #----------------------------------------------------------------------------
  # Dashboard / Frontend
  #----------------------------------------------------------------------------
  dashboard:
    build: ./dashboard
    ports:
      - "8082:80"
    volumes:
      - ./dashboard:/var/www/html
      - ./dashboard/php.ini:/usr/local/etc/php/php-dashboard.ini:ro
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres-data:
  zookeeper-data:
  zookeeper-datalog:
  grafana-data:
  prometheus-data:
